### ISSUE TITLE
Can not copy a theme

### ISSUE THREAD

**Issue by zhangciwu** [urvanov-ru/crayon-syntax-highlighter#11]
after click copy button, and input new name, and click OK,
A warning window shows, says "复制失败！ 更多信息请查看日志。"(copy failed, see log for more information)

But I checked, nothing logged

**Comment by urvanov-ru** [comment]
Yes, theme editor does not work now. I am trying to fix it now. Maybe it will be in next update.

**Comment by urvanov-ru** [comment]
Fixed in 2.8.10. Please check the update.

**Comment by zhangciwu** [comment]
Now I can copy theme successfully.

Some minor problems:
- After copy, didn't select the new one
- If new name has `-` or `_`, will be converted to space (and the letter next to it will be capitalized)
