### ISSUE TITLE
Pop out window is not showing the crayon theme

### ISSUE THREAD

**Issue by worldsdream** [urvanov-ru/crayon-syntax-highlighter#13]
Example:

Go to https://urvanov.ru/2020/05/18/первые-шаги-в-jupyterlab/

Click the pop out icon in the toolbar. That’s the last one in the top right corner. A new page will show up with the code. 

The theme is not showing. Its plain text. It should not be like that. 

Can you verify?

**Comment by urvanov-ru** [comment]
Yes, I see it now. Thank you. I wil l investigate it.

**Comment by worldsdream** [comment]
@urvanov-ru did you find anything related to this bug?

**Comment by urvanov-ru** [comment]
Don't worry I will fix it.

**Comment by worldsdream** [comment]
@urvanov-ru after the last update it’s working good on my website. 

When I check on your website, it’s not working. 

Did you fix this issue or why did it work at my end after the last update?

**Comment by urvanov-ru** [comment]
@worldsdream Yes, I fixed it. It should work.

It does not work only in MY site because of some issue with my site or cache or I updated plugin in my site too fast. But it is only the problem in my site. I checked fresh install and it worked well.

**Comment by worldsdream** [comment]
Yes, I can confirm it’s working on my site. I hope you get it working on your site!

I will close this issue. Thank you again.
