### ISSUE TITLE
About section update

### ISSUE THREAD

**Issue by worldsdream** [urvanov-ru/crayon-syntax-highlighter#14]
1. Please keep the "date" up to date in the about section --> 06th april, 2019 is wrong.

2. Please keep the names of the people that translated the plugin. But if the website is not working, remove the website. It's not good to have users click a link that's not working.

![firefox_M5PXr6iPQe](https://user-images.githubusercontent.com/12443285/84541837-73081d80-acf8-11ea-98fd-421dc9fcb755.png)

**Comment by worldsdream** [comment]
@urvanov-ru I think you fixed this right?

**Comment by urvanov-ru** [comment]
Yes, I think, I fixed it.
