### ISSUE TITLE
Upgrading from 2.8.8 upwards, breaks code snippets

### ISSUE THREAD

**Issue by CodeMazeBlog** [urvanov-ru/crayon-syntax-highlighter#18]
We are unable to upgrade from 2.8.8 to any higher version of the plugin since it completely breaks the snippets.
We can provide additional info if needed.

**Comment by urvanov-ru** [comment]
I need some example, what snippets do you use.

**Comment by urvanov-ru** [comment]
@CodeMazeBlog

**Comment by CodeMazeBlog** [comment]
Sorry, using enlighter.js now, too many problems with this plugin, and slow response time. Had to fix the other issue myself, but it's not worth it.

I've been using standard, C# formatted snippets, and whenever I upgraded to higher than 2.8.8 the whole website would show blank, unformatted snippets.

Can't provide you with more insight right now, unfortunately.
