### ISSUE TITLE
Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by rweijnen** [urvanov-ru/crayon-syntax-highlighter#23]
Using Wordpress 5.5.1 with PHP 7.4 I get the following Notice (with WP_DEBUG on) when unticking Custom Font Size:
`Notice: A non well formed numeric value encountered in /var/www/html/blog/wp-content/plugins/urvanov-syntax-highlighter/class-urvanov-syntax-highlighter-formatter.php on line 134
`
This is the code: `$line_height = ($font_size * 1.4) . 'px !important;';`

Maybe this should be: `$line_height = ($_font_size * 1.4) . 'px !important;';` ?

**Comment by urvanov-ru** [comment]
Fixed in 2.8.15
