### ISSUE TITLE
Syntax highlighter periodically stops working

### ISSUE THREAD

**Issue by sfsiegel** [urvanov-ru/crayon-syntax-highlighter#25]
The syntax highlighter looks great when it is working, but periodically it just stops working.   I add a new Urvanov block, save, and then preview it, and it just looks like plain unformatted text.  No matter how many times I re-load, etc., it doesn't change.   The actual HTML code, which I can see in the Code editor, looks fine (the block that begins "!-- wp:urvanov-syntax-highlighter/code-block --").
If I deactivate the plugin, and then reactivate it, the problem is solved.   I reload the page, and the formatting is there.  
It happens pretty often, so I find I have to constantly deactivate and then reactivate the plugin.
I am using the latest version of WordPress (5.6) and the plugin.  Theme is Libre.

**Comment by urvanov-ru** [comment]
Strange, I thought that I had fixed this. Ok. I will see, what is going on with Libre theme.

**Comment by urvanov-ru** [comment]
@sfsiegel Please, can you give me the list of all plugins in your website. I cannot reproduce this error in the fresh copy.

**Comment by sfsiegel** [comment]
Only one plugin: yours.  Urvanov Syntax Highlighter v.2.8.15.   Although I see there is a new version available now.
-Steve

**Comment by urvanov-ru** [comment]
Maybe some old PHP version? Can you provide other details, please? @sfsiegel
