### ISSUE TITLE
Thanks for a lot.

### ISSUE THREAD

**Issue by AcceptedDoge** [urvanov-ru/crayon-syntax-highlighter#3]
It works fine for my blog. Will you add more features in `code` blocks? 
I am not a PHP developer, so is there anything else I can help you with?

**Comment by urvanov-ru** [comment]
My forked version does not use code block. It uses special block named Urvanov Syntax Highlighter.

**Comment by AcceptedDoge** [comment]
I use the code block and then add custom CSS attributes as additional class according to [the document](https://github.com/urvanov-ru/crayon-syntax-highlighter#settings) to override global settings. Such as:

```
lang:scheme theme:twilight mark:1-5
```

It works. Thanks for your reminder, i will try the method you are using now.
