### ISSUE TITLE
Using "Copy" converts math characters to HTML entities

### ISSUE THREAD

**Issue by SteveDaulton** [urvanov-ru/crayon-syntax-highlighter#33]
Using the "Copy" button in a post and pasting into a text editor creates invalid code.
Example:
This Lisp code in post:
`(if (> hh 0) hh "")`
When copied and pasted into a plain text editor produces:
`(if (&gt; hh 0) hh "")`

To produce valid code, "Copy" needs to copy literal characters.

Version: Urvanov Syntax Highlighter 2.8.25
Platform: Ubuntu 20.04

**Comment by urvanov-ru** [comment]
Yes, you are right. Looks like a bug. I will fix it. Thank you.

**Comment by urvanov-ru** [comment]
Fixed in 2.8.26
