### ISSUE TITLE
The plugin incorrectly replaces the characters

### ISSUE THREAD

**Issue by igor-markin** [urvanov-ru/crayon-syntax-highlighter#35]
The plugin incorrectly replaces characters in some cases. For example:
- `self.records = &#91;]` instead of `self.records = []`
- `(today - record.date).days &lt; 7` instead of `(today - record.date).days < 7`

I encountered this problem in my [first article](https://juninja.ru/test-task-for-the-code-reviewer/).

![image](https://user-images.githubusercontent.com/74187064/144901400-d582a6ca-20b2-43a7-b167-6e9adbf9a87a.png)

**Comment by urvanov-ru** [comment]
@igor-markin I think you are using standard "code" block from Gutenberg. Don't use it. Use special "Urvanov Syntax Highlighter" block.
Add code blocks from the dialog as in the video:
https://www.youtube.com/watch?v=2aBtVJOOqqA

**Comment by igor-markin** [comment]
@urvanov-ru Спасибо 🙂
