### ISSUE TITLE
Bug report: when add `\(*)` in codes

### ISSUE THREAD

**Issue by AcceptedDoge** [urvanov-ru/crayon-syntax-highlighter#4]
It will show `{{urvanov-syntax-highlighter-internal:0}}`, I don't know how to fix it,

**Comment by urvanov-ru** [comment]
Accepted. I reproduced the bug. I will try to fix it as soon as possible.

**Comment by urvanov-ru** [comment]
Looks like some problem with mixed languages detection. As fast workaround you can try to turn off mixed languages checkbox in dialog box.
But I will try to fix it with the next update.

**Comment by AcceptedDoge** [comment]
> Looks like some problem with mixed languages detection. As fast workaround you can try to turn off mixed languages checkbox in dialog box.
> But I will try to fix it with the next update.

Thank you. It works now.

**Comment by urvanov-ru** [comment]
Fixed in 2.8.9. Please update you plugin and check.

**Comment by urvanov-ru** [comment]
@AcceptedDoge Fixed in 2.8.9. Please update the plugin and check.

**Comment by AcceptedDoge** [comment]
Thank you @urvanov-ru
