### ISSUE TITLE
[BUG] Duplicating theme error failed message

### ISSUE THREAD

**Issue by worldsdream** [urvanov-ru/crayon-syntax-highlighter#5]
![1234](https://user-images.githubusercontent.com/12443285/74720957-ec09d380-5236-11ea-8d95-79b78edc96d3.PNG)

**Comment by urvanov-ru** [comment]
Thank you. I know about this bug and I am on my way to fix it.

**Comment by worldsdream** [comment]
Thanks @urvanov-ru. I look forward for the update.

**Comment by urvanov-ru** [comment]
Fixed in 2.8.10. Please check the update.

**Comment by worldsdream** [comment]
I tried it and no more error. Great job.
Next time, please mention in the changelog that all custom themes need to be changed. I updated the plugin and my custom themes didn't work. Because you changed the CSS names. Thank you.
