### ISSUE TITLE
http links inside <pre> are not displayed correctly

### ISSUE THREAD

**Issue by kotyara12** [urvanov-ru/crayon-syntax-highlighter#52]
Good afternoon

How to “consciously” include a plugin in the text of an article?
If I enable processing of [pre] tags, then the site displays all such blocks as code.
But firstly, if inside the [pre] there is a link to the official documentation, say, then the html code of the link is displayed instead of the text, which is unacceptable.
Secondly, I don’t need to treat some [pre] as code. It needs to be left as is. I still don’t understand how to turn it off

I am completely happy with mini tags, but they are supposedly outdated and not supported. And they are not supported by the visual editor

What should I do?

**Comment by urvanov-ru** [comment]
The problem goes from old Crayon plugin.
I refactored it to use Gutenberg  but inside the plugin it still scans entire post text as a single article.
I should refactor it to scan only specific blocks using:
```
add_filter(
        'render_block',
        'Urvanov_Syntax_Highlighter_Plugin::my_custom_render',
        10,
        2 );
```
after that it would be work as expected in modern Gutenberg. I will do that once but it will not be soon.


As a workaround for now you can mark all pre tags that need to be pre tags and not blocks of code with CSS class crayon:false:

```
<pre class="crayon:false">
some pre
formatted
text
</pre>
```
Urvanov Syntax Highlighter plugin (old Crayon plugin) will skip all such pre tags and keep them as just formatted blocks without any plugin specific magic

**Comment by kotyara12** [comment]
There's just one problem: I'm NOT using the new Gutenberg. I blocked it everywhere on my website.
Does this mean that your plugin will not work correctly for me?

**Comment by urvanov-ru** [comment]
It can work with Gutenberg and with classic editor as well. But in Gutenberg it scans entire post test as in classic editor
